server:
  port: 8070
spring:
  application:
    name: MinusService
  cloud:
    nacos:
      discovery:
        server-addr: nacos.k8s:8848
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:10086/eureka

